name: svg_to_path_generator
description: Svg to path generator
version: 1.0.1+3
homepage: https://github.com/karabanovbs/svg_to_path_generator/tree/master/packages/svg_to_path_generator

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  build: ^2.3.1
  source_gen: ^1.2.7
  xml2json: ^5.3.6
  xml: ^6.2.2
  path_parsing: ^1.0.1
  analyzer: ^5.7.1
  svg_to_path_annotation: ^1.0.0

dev_dependencies:
  build_runner: ^2.3.3